/*
 * generated by Xtext
 */
package org.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.language.ui.internal.ReqLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReqLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ReqLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ReqLanguageActivator.getInstance().getInjector(ReqLanguageActivator.ORG_LANGUAGE_REQLANGUAGE);
	}
	
}
