/**
 * generated by Xtext
 */
package org.language.validation;

import org.language.validation.AbstractReqLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ReqLanguageValidator extends AbstractReqLanguageValidator {
}
