/*
 * generated by Xtext
 */
package org.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ReqLanguageUiModule extends org.language.ui.AbstractReqLanguageUiModule {
	public ReqLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
