/**
 * generated by Xtext
 */
package org.language.ui.contentassist;

import org.language.ui.contentassist.AbstractReqLanguageProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ReqLanguageProposalProvider extends AbstractReqLanguageProposalProvider {
}
