/*
 * generated by Xtext
 */
package org.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReqLanguageRuntimeModule extends org.language.AbstractReqLanguageRuntimeModule {

}
